FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    python-dev \
    gcc \
    libffi-dev \
    libssl-dev \
    python-pip \
    wget

RUN pip install --upgrade pip setuptools

#RUN pip install aria[ssh]

RUN pip install apache-ariatosca

WORKDIR /tmp

RUN wget https://github.com/apache/incubator-ariatosca/tree/master/examples/hello-world
