FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    python-dev \
    gcc \
    libffi-dev \
    libssl-dev \
    python-pip \
    git \
    wget

RUN pip install --upgrade pip setuptools

RUN pip install apache-ariatosca[ssh]

RUN pip install apache-ariatosca

WORKDIR /tmp

COPY helloworld.yaml .
