FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    python-dev \
    gcc \
    libffi-dev \
    libssl-dev \
    python-pip \
    git \
    wget

RUN pip install --upgrade pip setuptools

#RUN pip install apache-ariatosca

RUN pip install apache-ariatosca[ssh] --no-binary apache-ariatosca

WORKDIR /tmp

RUN git clone https://github.com/apache/incubator-ariatosca.git /tmp/incubator-ariatosca

RUN sed -i "s/tosca:Root/tosca.nodes.Root/g" /tmp/incubator-ariatosca/examples/hello-world/helloworld.yaml
