FROM centos:6.6

RUN yum -y update; yum clean all

RUN yum install -y yum-plugin-ovl
RUN yum install -y python-devel 
RUN yum install -y gcc
RUN yum install -y libffi-devel
RUN yum install -y openssl-devel
RUN yum install -y epel-release
RUN yum install -y python-pip
RUN yum install -y git 

RUN pip install virtualenv

WORKDIR /tmp

RUN virtualenv aria_project

RUN source aria_project/bin/activate

RUN pip install --upgrade pip setuptools

#RUN pip install apache-ariatosca 

RUN pip install apache-ariatosca[ssh] --no-binary apache-ariatosca

RUN git clone https://github.com/apache/incubator-ariatosca.git /tmp/incubator-ariatosca

RUN sed -i "s/tosca:Root/tosca.nodes.Root/g" /tmp/incubator-ariatosca/examples/hello-world/helloworld.yaml
