---

- apt_repository:
    repo: "{{ java_openjdk_repo }}"
    state: present

- name: Install OpenJDK Java
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ java_debian_openjdk_packages[java_version] }}"
